services:

  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME:-django_db}
      MYSQL_USER: ${DB_USER:-sawjal}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app_network

  web:
    build: .
    restart: unless-stopped
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=${DB_NAME:-django_db}
      - DB_USER=${DB_USER:-sawjal}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_HOST=db
      - DB_PORT=3306
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=your_secret_key_here
      - DEBUG=True
      - ALLOWED_HOSTS=*
    depends_on:
      - db
      - redis
    networks:
      - app_network

  celery_worker:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    environment:
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=${DB_NAME:-django_db}
      - DB_USER=${DB_USER:-sawjal}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_HOST=db
      - DB_PORT=3306
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=your_secret_key_here
      - DEBUG=True
    depends_on:
      - db
      - redis
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge