# Generated by Django 6.1 on 2026-08-24 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationmembership',
            name='unique_user_company_membership',
        ),
        migrations.RenameField(
            model_name='organizationmembership',
            old_name='company',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_organization_membership'),
        ),
    ]
