# Generated by Django 6.1 on 2026-09-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroup',
            name='group_type',
            field=models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('cogs', 'Cost of Goods Sold'), ('expense', 'Expense')], max_length=20),
        ),
    ]
