# Generated by Django 6.1 on 2026-08-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_created_by_account_updated_by_and_more'),
        ('authentication', '0005_alter_user_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
