# Generated by Django 6.1 on 2026-08-25 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_organization'),
        ('organization', '0003_permission_role_rolepermission_userrole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroup',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_groups', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='group_type',
            field=models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('cogs', 'Cost of Goods Sold'), ('expense', 'Expense')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='accountgroup',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_group_code_per_organization'),
        ),
    ]
