# Generated by Django 6.1 on 2026-09-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountgroup_group_type'),
        ('accounts', '0005_account_organization_accountgroup_organization_and_more'),
    ]

    operations = [
    ]
