# Generated by Django 6.1 on 2026-09-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260912_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='type_of_journal',
            field=models.CharField(choices=[('general', 'General'), ('sales', 'Sales'), ('sales_return', 'Sales Return'), ('purchase', 'Purchase'), ('purchase_return', 'Purchase Return'), ('received_payment', 'Received Payment'), ('made_payment', 'Made Payment'), ('contra', 'Contra'), ('expense', 'Expense'), ('income', 'Income'), ('payroll', 'Payroll'), ('tax', 'Tax'), ('depreciation', 'Depreciation'), ('accrual', 'Accrual'), ('prepayment', 'Prepayment'), ('inventory', 'Inventory'), ('adjustment', 'Adjustment'), ('opening_balance', 'Opening Balance'), ('closing', 'Closing'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('refund', 'Refund'), ('write_off', 'Write Off'), ('transfer', 'Transfer'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
